default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

production:
  <<: *default
  pool: <%= ENV['DB_POOL_SIZE'] || 30 %>
  database: <%= ENV['RDS_DB_NAME'] || ENV['PG_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] || ENV['PG_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] || ENV['PG_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] || ENV['PG_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] || ENV['PG_PORT'] %>
